// Generated by go run ./tools generate. Do not edit by hand.
import c0l0 from "../content/cases/fs-c02/locales/en.json";
import c0l1 from "../content/cases/fs-c02/locales/zh-TW.json";
import c0l2 from "../content/cases/fs-c02/locales/zh-CN.json";
import c0l3 from "../content/cases/fs-c02/locales/ja.json";
import c0l4 from "../content/cases/fs-c02/locales/ko.json";
import c0l5 from "../content/cases/fs-c02/locales/es.json";
import c0l6 from "../content/cases/fs-c02/locales/fr.json";
import c0l7 from "../content/cases/fs-c02/locales/de.json";
import c0l8 from "../content/cases/fs-c02/locales/pt-BR.json";
import c0l9 from "../content/cases/fs-c02/locales/it.json";
import c0l10 from "../content/cases/fs-c02/locales/nl.json";
import c0l11 from "../content/cases/fs-c02/locales/pl.json";
import c0l12 from "../content/cases/fs-c02/locales/tr.json";
import c0l13 from "../content/cases/fs-c02/locales/uk.json";
import c0l14 from "../content/cases/fs-c02/locales/ru.json";
import c0l15 from "../content/cases/fs-c02/locales/ar.json";
import c0l16 from "../content/cases/fs-c02/locales/hi.json";
import c0l17 from "../content/cases/fs-c02/locales/vi.json";
import c0l18 from "../content/cases/fs-c02/locales/th.json";
import c0l19 from "../content/cases/fs-c02/locales/id.json";
import c1l0 from "../content/cases/fs-c03/locales/en.json";
import c1l1 from "../content/cases/fs-c03/locales/zh-TW.json";
import c1l2 from "../content/cases/fs-c03/locales/zh-CN.json";
import c1l3 from "../content/cases/fs-c03/locales/ja.json";
import c1l4 from "../content/cases/fs-c03/locales/ko.json";
import c1l5 from "../content/cases/fs-c03/locales/es.json";
import c1l6 from "../content/cases/fs-c03/locales/fr.json";
import c1l7 from "../content/cases/fs-c03/locales/de.json";
import c1l8 from "../content/cases/fs-c03/locales/pt-BR.json";
import c1l9 from "../content/cases/fs-c03/locales/it.json";
import c1l10 from "../content/cases/fs-c03/locales/nl.json";
import c1l11 from "../content/cases/fs-c03/locales/pl.json";
import c1l12 from "../content/cases/fs-c03/locales/tr.json";
import c1l13 from "../content/cases/fs-c03/locales/uk.json";
import c1l14 from "../content/cases/fs-c03/locales/ru.json";
import c1l15 from "../content/cases/fs-c03/locales/ar.json";
import c1l16 from "../content/cases/fs-c03/locales/hi.json";
import c1l17 from "../content/cases/fs-c03/locales/vi.json";
import c1l18 from "../content/cases/fs-c03/locales/th.json";
import c1l19 from "../content/cases/fs-c03/locales/id.json";
import c2l0 from "../content/cases/fs-c04/locales/en.json";
import c2l1 from "../content/cases/fs-c04/locales/zh-TW.json";
import c2l2 from "../content/cases/fs-c04/locales/zh-CN.json";
import c2l3 from "../content/cases/fs-c04/locales/ja.json";
import c2l4 from "../content/cases/fs-c04/locales/ko.json";
import c2l5 from "../content/cases/fs-c04/locales/es.json";
import c2l6 from "../content/cases/fs-c04/locales/fr.json";
import c2l7 from "../content/cases/fs-c04/locales/de.json";
import c2l8 from "../content/cases/fs-c04/locales/pt-BR.json";
import c2l9 from "../content/cases/fs-c04/locales/it.json";
import c2l10 from "../content/cases/fs-c04/locales/nl.json";
import c2l11 from "../content/cases/fs-c04/locales/pl.json";
import c2l12 from "../content/cases/fs-c04/locales/tr.json";
import c2l13 from "../content/cases/fs-c04/locales/uk.json";
import c2l14 from "../content/cases/fs-c04/locales/ru.json";
import c2l15 from "../content/cases/fs-c04/locales/ar.json";
import c2l16 from "../content/cases/fs-c04/locales/hi.json";
import c2l17 from "../content/cases/fs-c04/locales/vi.json";
import c2l18 from "../content/cases/fs-c04/locales/th.json";
import c2l19 from "../content/cases/fs-c04/locales/id.json";
import c3l0 from "../content/cases/fs-c05/locales/en.json";
import c3l1 from "../content/cases/fs-c05/locales/zh-TW.json";
import c3l2 from "../content/cases/fs-c05/locales/zh-CN.json";
import c3l3 from "../content/cases/fs-c05/locales/ja.json";
import c3l4 from "../content/cases/fs-c05/locales/ko.json";
import c3l5 from "../content/cases/fs-c05/locales/es.json";
import c3l6 from "../content/cases/fs-c05/locales/fr.json";
import c3l7 from "../content/cases/fs-c05/locales/de.json";
import c3l8 from "../content/cases/fs-c05/locales/pt-BR.json";
import c3l9 from "../content/cases/fs-c05/locales/it.json";
import c3l10 from "../content/cases/fs-c05/locales/nl.json";
import c3l11 from "../content/cases/fs-c05/locales/pl.json";
import c3l12 from "../content/cases/fs-c05/locales/tr.json";
import c3l13 from "../content/cases/fs-c05/locales/uk.json";
import c3l14 from "../content/cases/fs-c05/locales/ru.json";
import c3l15 from "../content/cases/fs-c05/locales/ar.json";
import c3l16 from "../content/cases/fs-c05/locales/hi.json";
import c3l17 from "../content/cases/fs-c05/locales/vi.json";
import c3l18 from "../content/cases/fs-c05/locales/th.json";
import c3l19 from "../content/cases/fs-c05/locales/id.json";
import c4l0 from "../content/cases/fs-c06/locales/en.json";
import c4l1 from "../content/cases/fs-c06/locales/zh-TW.json";
import c4l2 from "../content/cases/fs-c06/locales/zh-CN.json";
import c4l3 from "../content/cases/fs-c06/locales/ja.json";
import c4l4 from "../content/cases/fs-c06/locales/ko.json";
import c4l5 from "../content/cases/fs-c06/locales/es.json";
import c4l6 from "../content/cases/fs-c06/locales/fr.json";
import c4l7 from "../content/cases/fs-c06/locales/de.json";
import c4l8 from "../content/cases/fs-c06/locales/pt-BR.json";
import c4l9 from "../content/cases/fs-c06/locales/it.json";
import c4l10 from "../content/cases/fs-c06/locales/nl.json";
import c4l11 from "../content/cases/fs-c06/locales/pl.json";
import c4l12 from "../content/cases/fs-c06/locales/tr.json";
import c4l13 from "../content/cases/fs-c06/locales/uk.json";
import c4l14 from "../content/cases/fs-c06/locales/ru.json";
import c4l15 from "../content/cases/fs-c06/locales/ar.json";
import c4l16 from "../content/cases/fs-c06/locales/hi.json";
import c4l17 from "../content/cases/fs-c06/locales/vi.json";
import c4l18 from "../content/cases/fs-c06/locales/th.json";
import c4l19 from "../content/cases/fs-c06/locales/id.json";
import c5l0 from "../content/cases/fs-c07/locales/en.json";
import c5l1 from "../content/cases/fs-c07/locales/zh-TW.json";
import c5l2 from "../content/cases/fs-c07/locales/zh-CN.json";
import c5l3 from "../content/cases/fs-c07/locales/ja.json";
import c5l4 from "../content/cases/fs-c07/locales/ko.json";
import c5l5 from "../content/cases/fs-c07/locales/es.json";
import c5l6 from "../content/cases/fs-c07/locales/fr.json";
import c5l7 from "../content/cases/fs-c07/locales/de.json";
import c5l8 from "../content/cases/fs-c07/locales/pt-BR.json";
import c5l9 from "../content/cases/fs-c07/locales/it.json";
import c5l10 from "../content/cases/fs-c07/locales/nl.json";
import c5l11 from "../content/cases/fs-c07/locales/pl.json";
import c5l12 from "../content/cases/fs-c07/locales/tr.json";
import c5l13 from "../content/cases/fs-c07/locales/uk.json";
import c5l14 from "../content/cases/fs-c07/locales/ru.json";
import c5l15 from "../content/cases/fs-c07/locales/ar.json";
import c5l16 from "../content/cases/fs-c07/locales/hi.json";
import c5l17 from "../content/cases/fs-c07/locales/vi.json";
import c5l18 from "../content/cases/fs-c07/locales/th.json";
import c5l19 from "../content/cases/fs-c07/locales/id.json";

export const catalogs = {
  "fs-c02": {
    en: c0l0.messages,
    "zh-TW": c0l1.messages,
    "zh-CN": c0l2.messages,
    ja: c0l3.messages,
    ko: c0l4.messages,
    es: c0l5.messages,
    fr: c0l6.messages,
    de: c0l7.messages,
    "pt-BR": c0l8.messages,
    it: c0l9.messages,
    nl: c0l10.messages,
    pl: c0l11.messages,
    tr: c0l12.messages,
    uk: c0l13.messages,
    ru: c0l14.messages,
    ar: c0l15.messages,
    hi: c0l16.messages,
    vi: c0l17.messages,
    th: c0l18.messages,
    id: c0l19.messages,
  },
  "fs-c03": {
    en: c1l0.messages,
    "zh-TW": c1l1.messages,
    "zh-CN": c1l2.messages,
    ja: c1l3.messages,
    ko: c1l4.messages,
    es: c1l5.messages,
    fr: c1l6.messages,
    de: c1l7.messages,
    "pt-BR": c1l8.messages,
    it: c1l9.messages,
    nl: c1l10.messages,
    pl: c1l11.messages,
    tr: c1l12.messages,
    uk: c1l13.messages,
    ru: c1l14.messages,
    ar: c1l15.messages,
    hi: c1l16.messages,
    vi: c1l17.messages,
    th: c1l18.messages,
    id: c1l19.messages,
  },
  "fs-c04": {
    en: c2l0.messages,
    "zh-TW": c2l1.messages,
    "zh-CN": c2l2.messages,
    ja: c2l3.messages,
    ko: c2l4.messages,
    es: c2l5.messages,
    fr: c2l6.messages,
    de: c2l7.messages,
    "pt-BR": c2l8.messages,
    it: c2l9.messages,
    nl: c2l10.messages,
    pl: c2l11.messages,
    tr: c2l12.messages,
    uk: c2l13.messages,
    ru: c2l14.messages,
    ar: c2l15.messages,
    hi: c2l16.messages,
    vi: c2l17.messages,
    th: c2l18.messages,
    id: c2l19.messages,
  },
  "fs-c05": {
    en: c3l0.messages,
    "zh-TW": c3l1.messages,
    "zh-CN": c3l2.messages,
    ja: c3l3.messages,
    ko: c3l4.messages,
    es: c3l5.messages,
    fr: c3l6.messages,
    de: c3l7.messages,
    "pt-BR": c3l8.messages,
    it: c3l9.messages,
    nl: c3l10.messages,
    pl: c3l11.messages,
    tr: c3l12.messages,
    uk: c3l13.messages,
    ru: c3l14.messages,
    ar: c3l15.messages,
    hi: c3l16.messages,
    vi: c3l17.messages,
    th: c3l18.messages,
    id: c3l19.messages,
  },
  "fs-c06": {
    en: c4l0.messages,
    "zh-TW": c4l1.messages,
    "zh-CN": c4l2.messages,
    ja: c4l3.messages,
    ko: c4l4.messages,
    es: c4l5.messages,
    fr: c4l6.messages,
    de: c4l7.messages,
    "pt-BR": c4l8.messages,
    it: c4l9.messages,
    nl: c4l10.messages,
    pl: c4l11.messages,
    tr: c4l12.messages,
    uk: c4l13.messages,
    ru: c4l14.messages,
    ar: c4l15.messages,
    hi: c4l16.messages,
    vi: c4l17.messages,
    th: c4l18.messages,
    id: c4l19.messages,
  },
  "fs-c07": {
    en: c5l0.messages,
    "zh-TW": c5l1.messages,
    "zh-CN": c5l2.messages,
    ja: c5l3.messages,
    ko: c5l4.messages,
    es: c5l5.messages,
    fr: c5l6.messages,
    de: c5l7.messages,
    "pt-BR": c5l8.messages,
    it: c5l9.messages,
    nl: c5l10.messages,
    pl: c5l11.messages,
    tr: c5l12.messages,
    uk: c5l13.messages,
    ru: c5l14.messages,
    ar: c5l15.messages,
    hi: c5l16.messages,
    vi: c5l17.messages,
    th: c5l18.messages,
    id: c5l19.messages,
  },
} as const;
