// Generated by go run ./tools generate. Do not edit by hand.
import c0l0 from "../content/cases/fs-c02/locales/en.json";
import c0l1 from "../content/cases/fs-c02/locales/zh-TW.json";
import c0l2 from "../content/cases/fs-c02/locales/zh-CN.json";
import c0l3 from "../content/cases/fs-c02/locales/ja.json";
import c0l4 from "../content/cases/fs-c02/locales/ko.json";
import c0l5 from "../content/cases/fs-c02/locales/es.json";
import c0l6 from "../content/cases/fs-c02/locales/fr.json";
import c0l7 from "../content/cases/fs-c02/locales/de.json";
import c0l8 from "../content/cases/fs-c02/locales/pt-BR.json";
import c0l9 from "../content/cases/fs-c02/locales/it.json";
import c0l10 from "../content/cases/fs-c02/locales/nl.json";
import c0l11 from "../content/cases/fs-c02/locales/pl.json";
import c0l12 from "../content/cases/fs-c02/locales/tr.json";
import c0l13 from "../content/cases/fs-c02/locales/uk.json";
import c0l14 from "../content/cases/fs-c02/locales/ru.json";
import c0l15 from "../content/cases/fs-c02/locales/ar.json";
import c0l16 from "../content/cases/fs-c02/locales/hi.json";
import c0l17 from "../content/cases/fs-c02/locales/vi.json";
import c0l18 from "../content/cases/fs-c02/locales/th.json";
import c0l19 from "../content/cases/fs-c02/locales/id.json";
import c1l0 from "../content/cases/fs-c03/locales/en.json";
import c1l1 from "../content/cases/fs-c03/locales/zh-TW.json";
import c1l2 from "../content/cases/fs-c03/locales/zh-CN.json";
import c1l3 from "../content/cases/fs-c03/locales/ja.json";
import c1l4 from "../content/cases/fs-c03/locales/ko.json";
import c1l5 from "../content/cases/fs-c03/locales/es.json";
import c1l6 from "../content/cases/fs-c03/locales/fr.json";
import c1l7 from "../content/cases/fs-c03/locales/de.json";
import c1l8 from "../content/cases/fs-c03/locales/pt-BR.json";
import c1l9 from "../content/cases/fs-c03/locales/it.json";
import c1l10 from "../content/cases/fs-c03/locales/nl.json";
import c1l11 from "../content/cases/fs-c03/locales/pl.json";
import c1l12 from "../content/cases/fs-c03/locales/tr.json";
import c1l13 from "../content/cases/fs-c03/locales/uk.json";
import c1l14 from "../content/cases/fs-c03/locales/ru.json";
import c1l15 from "../content/cases/fs-c03/locales/ar.json";
import c1l16 from "../content/cases/fs-c03/locales/hi.json";
import c1l17 from "../content/cases/fs-c03/locales/vi.json";
import c1l18 from "../content/cases/fs-c03/locales/th.json";
import c1l19 from "../content/cases/fs-c03/locales/id.json";

export const catalogs = {
  "fs-c02": {
    en: c0l0.messages,
    "zh-TW": c0l1.messages,
    "zh-CN": c0l2.messages,
    ja: c0l3.messages,
    ko: c0l4.messages,
    es: c0l5.messages,
    fr: c0l6.messages,
    de: c0l7.messages,
    "pt-BR": c0l8.messages,
    it: c0l9.messages,
    nl: c0l10.messages,
    pl: c0l11.messages,
    tr: c0l12.messages,
    uk: c0l13.messages,
    ru: c0l14.messages,
    ar: c0l15.messages,
    hi: c0l16.messages,
    vi: c0l17.messages,
    th: c0l18.messages,
    id: c0l19.messages,
  },
  "fs-c03": {
    en: c1l0.messages,
    "zh-TW": c1l1.messages,
    "zh-CN": c1l2.messages,
    ja: c1l3.messages,
    ko: c1l4.messages,
    es: c1l5.messages,
    fr: c1l6.messages,
    de: c1l7.messages,
    "pt-BR": c1l8.messages,
    it: c1l9.messages,
    nl: c1l10.messages,
    pl: c1l11.messages,
    tr: c1l12.messages,
    uk: c1l13.messages,
    ru: c1l14.messages,
    ar: c1l15.messages,
    hi: c1l16.messages,
    vi: c1l17.messages,
    th: c1l18.messages,
    id: c1l19.messages,
  },
} as const;
