package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The frontend imports a generated registry. Adding a Case does not require
// another hand-maintained block of twenty static JSON imports.
func generateExtraCaseCatalogs() error {
	registryBytes, err := os.ReadFile("web/i18n/registry.json")
	if err != nil {
		return err
	}
	var locales []struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(registryBytes, &locales); err != nil {
		return err
	}
	var output strings.Builder
	output.WriteString("// Generated by go run ./tools generate. Do not edit by hand.\n")
	caseIDs := []string{"fs-c02", "fs-c03", "fs-c04", "fs-c05", "fs-c06", "fs-c07", "fs-c08"}
	for caseIndex, caseID := range caseIDs {
		for localeIndex, locale := range locales {
			path := filepath.Join("web", "content", "cases", caseID, "locales", locale.ID+".json")
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			var catalog struct {
				CaseID   string            `json:"caseId"`
				Messages map[string]string `json:"messages"`
			}
			if err := json.Unmarshal(data, &catalog); err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if catalog.CaseID != caseID {
				return fmt.Errorf("%s: expected caseId %s", path, caseID)
			}
			fmt.Fprintf(&output, "import c%dl%d from %q;\n", caseIndex, localeIndex, "../content/cases/"+caseID+"/locales/"+locale.ID+".json")
		}
	}
	output.WriteString("\nexport const catalogs = {\n")
	for caseIndex, caseID := range caseIDs {
		fmt.Fprintf(&output, "  %q: {\n", caseID)
		for localeIndex, locale := range locales {
			key := locale.ID
			if strings.Contains(key, "-") {
				key = fmt.Sprintf("%q", key)
			}
			fmt.Fprintf(&output, "    %s: c%dl%d.messages,\n", key, caseIndex, localeIndex)
		}
		output.WriteString("  },\n")
	}
	output.WriteString("} as const;\n")
	return os.WriteFile("web/i18n/generated-extra-cases.ts", []byte(output.String()), 0644)
}
